{
 "title": "Traefik - Access",
 "tags": [
  "App",
  "Traefik"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "front",
    "label": "Frontend",
    "query": "{\"find\":\"terms\", \"field\":\"traefik.access.frontend_name\", \"query\": \"source.geo.country_iso_code: * \"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\":\"terms\", \"field\":\"host.name\", \"query\": \"traefik.access.frontend_name: *\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Traefik - Access Log  - Top International",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "8",
       "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "traefik.access.frontend_name: $front  AND source.geo.country_iso_code: * AND NOT source.geo.country_iso_code: US AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traefik - Access Log  - Top Frontends",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "traefik.access.frontend_name",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "8",
       "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "traefik.access.frontend_name: * AND NOT http.response.status_code: 200 AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traefik - Access Log  - Response Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.response.status_code",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "8",
       "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "traefik.access.frontend_name: $front AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traefik - $front",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "source.geo.country_iso_code: * AND traefik.access.frontend_name: $front AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access Log - $front",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "source.geo.region_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "source.geo.city_name",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "traefik.access.frontend_name: $front AND source.geo.country_iso_code: * AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access Log - $front",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source.address",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "traefik.access.frontend_name: $front AND source.geo.country_iso_code: * AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Codes - $front",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.response.status_code",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "source.address",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "htt",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "traefik.access.frontend_name: $front AND NOT http.response.status_code: 200 AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Code - $front",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.response.status_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "traefik.access.frontend_name: $front AND source.geo.country_iso_code: * AND host.name: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "content": "\n#### Option\n\n* backend not found - any connection that hits our WAN IP without Cloudflare (\"malicious\" scanners)\n\n\n\n\n"
  }
 ]
}